survey_site/survey/urls.py
from django.urls import path
from . import views

app_name = 'survey'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

survey_site/survey_site/urls.py
from django.contrib import admin
from django.urls import path, include
from survey import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('survey/', include('survey.urls'))
]

survey_site/survey/models.py
from django.db import models

# Create your models here.
class Survey(models.Model):
    name = models.CharField(max_length = 200)

    def __str__(self):
        return self.name

class SurveyQuestion(models.Model):
    question_text = models.CharField(max_length = 300)
    survey = models.ForeignKey(Survey, on_delete = models.CASCADE)

    def __str__(self):
        return self.question_text

class SurveyChoice(models.Model):
    choice_text = models.CharField(max_length = 300)
    surveyquestion = models.ForeignKey(SurveyQuestion, on_delete = models.CASCADE)
    surveychoice = models.ForeignKey(Survey, on_delete = models.CASCADE)
    selection_amount = models.IntegerField(default = 0)

    def __str__(self):
        return self.choice_text

survey_site/survey/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.template import loader
from django.urls import reverse
from django.views import generic
from .models import *

class IndexView(generic.ListView):
    template_name = 'survey/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return all the questions."""
        return SurveyQuestion.objects.all()

survey_site/survey/templates/survey/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'survey/style.css' %}" />

<h1> {2018 Western Union Compliance Agent Survey} </h1>

{% if latest_question_list %}
<form method="post">{% csrf_token %}
  <ul>
    {% for surveyquestion in latest_question_list %}
      <li>
        {{ surveyquestion.question_text }}
        {% for surveychoice in surveyquestion.surveychoice_set.all %}
            <br />
            {% if surveychoice.id == 1 %}
              <label for = "choice {{ forloop.counter}}">{{surveychoice.choice_text }} </label><br />
              <input type = "text" name = "choice" id = "choice {{forloop.counter }}"/>
            {% else %}
              <input type = "checkbox" name = "choice" id = "choice {{forloop.counter }}" value = "{{ surveychoice.id }}" />
              <label for = "choice {{ forloop.counter}}">{{surveychoice.choice_text }} </label><br />
            {% endif %}
        {% endfor %}
        <br />
      </li>
      <br />
    {% endfor %}
    <input type = "submit" value = "Submit" />
  </ul>
</form>
{% else %}
  <p> No questions are currently assigned. </p>
{% endif %}